name: Python test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create necessary files and directories
      run: |
        mkdir -p clearurl/rules
        touch clearurl/rules/adguard_rules.yaml
        touch clearurl/rules/custom_rules.yaml
        touch clearurl/rules/default_rules.yaml
        if [ ! -f README.md ] && [ -f readme.md ]; then
          cp readme.md README.md
        elif [ ! -f readme.md ] && [ -f README.md ]; then
          cp README.md readme.md
        elif [ ! -f README.md ] && [ ! -f readme.md ]; then
          echo "# ClearURL" > README.md
          echo "# ClearURL" > readme.md
        fi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    - name: Test with pytest
      run: |
        pytest --cov=clearurl
    - name: Check package build
      run: |
        pip install build
        python -m build